
version: '3.8'
services:
  db:
    user: "postgres"
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5432:5432'
    volumes: 
      - db:/var/lib/postgresql/data
    # network_mode: bridge
    healthcheck:
      test: ["CMD", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - backend
  redis:
    build: ./redis
    depends_on:
      - db
    networks:
      - backend
    
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - 22181:2181
    networks:
      - backend  
    
  kafka_0:
    image: confluentinc/cp-kafka:latest
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      HOSTNAME_COMMAND: "docker info | grep ^Name: | cut -d' ' -f 2"
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka_0:9092,PLAINTEXT_HOST1://kafka:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST1:PLAINTEXT
    healthcheck:
      test: nc -z localhost 9092 || exit -1 
      interval: 15s
      timeout: 10s
      retries: 5  
    networks:
      - backend
  kafka_1:
    image: confluentinc/cp-kafka:latest
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 2
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      HOSTNAME_COMMAND: "docker info | grep ^Name: | cut -d' ' -f 2"
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka_1:9093,PLAINTEXT_HOST1://kafka:29093
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST1:PLAINTEXT
    healthcheck:
      test: nc -z localhost 9093 || exit -1 
      interval: 15s
      timeout: 10s
      retries: 5  
    networks:
      - backend
  kafka_2:
    image: confluentinc/cp-kafka:latest
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 3
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      HOSTNAME_COMMAND: "docker info | grep ^Name: | cut -d' ' -f 2"
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka_2:9094,PLAINTEXT_HOST1://kafka:29094
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST1:PLAINTEXT
    healthcheck:
      test: nc -z localhost 9094 || exit -1 
      interval: 15s
      timeout: 10s
      retries: 5  
    networks:
      - backend
  api:
    build: ./tmanagement
    environment:
      DBADDR: "db"
    expose:
      # - 5432
      - 8080
    ports:
      - 8080:8080
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_started
      serv2:
        condition: service_started
    # network_mode: bridge
    networks:
      - backend
  serv2:
    build: ./durationCount
    environment:
      DBADDR: "db"
    # expose:
      # - 5432
      # - 8080
    # ports:
      # - 8080:8080
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_started
    # network_mode: bridge
    networks:
      - backend
volumes:
  db:
    driver: local
networks:
  backend:
    driver: 
      bridge
    