version: '3.8'
services:
  db:
    user: "postgres"
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5432:5432'
    volumes: 
      - db:/var/lib/postgresql/data
    # network_mode: bridge
    healthcheck:
      test: ["CMD", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - backend
  redis:
    build: ./redis
    depends_on:
      - db
    networks:
      - backend
    
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - 22181:2181
    networks:
      - backend  
  kafka:
    image: confluentinc/cp-kafka:latest
    depends_on:
      - zookeeper
    ports:
      - 29092:29092
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_CREATE_TOPICS: "test:1:1"
    healthcheck:
      test: nc -z localhost 9092 || exit -1 
      interval: 15s
      timeout: 10s
      retries: 5  
    networks:
      - backend   
  api:
    build: ./tmanagement
    environment:
      DBADDR: "db"
    expose:
      # - 5432
      - 8080
    ports:
      - 8080:8080
    depends_on:
      db:
        condition: service_healthy
      kafka:
        condition: service_healthy
      redis:
        condition: service_started
      serv2:
        condition: service_started
    # network_mode: bridge
    networks:
      - backend
  serv2:
    build: ./durationCount
    environment:
      DBADDR: "db"
    # expose:
      # - 5432
      # - 8080
    # ports:
      # - 8080:8080
    depends_on:
      db:
        condition: service_healthy
      kafka:
        condition: service_healthy
      redis:
        condition: service_started
    # network_mode: bridge
    networks:
      - backend
volumes:
  db:
    driver: local
networks:
  backend:
    driver: 
      bridge