version: '3.8'
services:
  db:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5432:5432'
    volumes: 
      - db:/var/lib/postgresql/data
    # network_mode: bridge
    networks:
      - backend
  api:
    build: ./tmanagement
    expose:
      # - 5432
      - 8080
    ports:
      - 8080:8080
    depends_on:
      - db
    # network_mode: bridge
    networks:
      - backend
volumes:
  db:
    driver: local
networks:
  backend:
    driver: 
      bridge